#!/bin/bash
c=$1
if [ $1 = "right" ]
	then
		c=50
fi
if [ $1 = "left" ]
	then
		c=0
fi
b=95
a=50
d=0
n=`xdotool getactivewindow getwindowname`
if [[ "$n" == *" - Google Chrome"* ]] || [[ "$n" == *" - Chromium"* ]]
	then
		b=96
fi
if [[ "$n" == *" - LibreOffice"* ]]
	then
		d=3
		b=93
fi
wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
xdotool getactivewindow windowsize $a% $b%
xdotool getactivewindow windowmove $c% $d%
